# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u4MFz9pIalk61H5kFD1PnenTtWfozKRk
"""
from flask import Flask, request, jsonify

app = Flask(__name__)

@app.route('/home', methods=['GET'])
def hello():
    return "hello. send me an api request to /sum using response = requests.get(url, params=params), where params = {'num1': num1, 'num2': num2} and I will calculate a sum of those 2 numbers, however large or small :)"
@app.route('/sum', methods=['GET'])
def calculate_sum():
    # Get numbers from query parameters
    num1 = request.args.get('num1', type=float)
    num2 = request.args.get('num2', type=float)

    if num1 is None or num2 is None:
        return jsonify({"error": "Please provide both num1 and num2"}), 400

    # Calculate the sum
    result = num1 + num2
    return jsonify({"sum": result})

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=5000)
